services:
  telemetry:
    container_name: artemis-telemetry
    image: ls1tum/artemis-telemetry:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/telemetry.env
    ports:
      - '127.0.0.1:8080:8080'
    expose:
      - '8080'
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:8080/management/health || exit 1
      start_period: 600s
      interval: 1s
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    container_name: mysql
    image: mysql:9.0.1
    volumes:
      - artemis-telemetry-mysql-data:/var/lib/mysql
    env_file:
      - config/mysql.env
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --tls-version='' --character_set_server=utf8mb4  --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --silent
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 300s
    restart: always

volumes:
  artemis-telemetry-mysql-data:
    name: artemis-telemetry-mysql-data